version: "3.9"

services:
  mongodb:
    image: mongo:6
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  backend:
    build: ./Backend
    container_name: backend
    image: sunjay195/backend:latest
    depends_on:
      - mongodb
      - redis
    env_file:
      - ./Backend/.env
    environment:
      - MONGO_DB_URI=mongodb://mongodb:27017/cron-job
      - REDIS_URL=redis://redis:6379
    ports:
      - "3000:3000"
    networks:
      - app-network
    
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  frontend:
    build: ./Frontend
    container_name: frontend
    image: sunjay195/frontend:latest
    depends_on:
      - backend
    env_file:
      - ./Frontend/.env
    ports:
      - "5173:5173"
    networks:
      - app-network
  
  email-service:
    build: ./email-service
    container_name: email-service
    image: sunjay195/email-service:latest
    depends_on:
      - backend
    env_file:
      - ./email-service/.env
    ports:
      - "3001:3001"
    networks:
      - app-network
  
  job-runner:
    build: ./job-runner
    container_name: job-runner
    image: sunjay195/job-runner:latest
    depends_on:
      - mongodb
    env_file:
      - ./job-runner/.env
    environment:
      - MONGO_DB_URI=mongodb://mongodb:27017/cron-job
    ports:
    - "3002:3002"
    networks:
      - app-network
  
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge